<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Activare cont</title>
        <!-- <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'> -->
        <style>
            body {
                /*margin: 50px 0 0 0;*/
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #039BE5;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 50px;
                font-weight: 200;
                margin-bottom: 0;
            }

            .response {
                color: #8B0000;
                font-size: 30px;
            }
        </style>
    </head>
    <body>
        <h1>Kumparaturi</h1>
        <div>(aplicatia care mananca bani)</div>
        <br>
        <div class="response"><?php echo $reason ?></div>
    </body>
</html>
